INSERT INTO Albums (name, path) VALUES ('Chopin Etudes', null);
INSERT INTO Playlists (name) VALUES ('Favorite Chopin Etudes');

INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 10 no. 1 in C major', 'Edward Neeman', null, 0, 'music/Chopin Etudes/Etude Op. 10 no. 1 in C major.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 10 no. 2 in A minor', 'Edward Neeman', null, 1, 'music/Chopin Etudes/Etude Op. 10 no. 2 in A minor.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 10 no. 3 in E major', 'Edward Neeman', null, 2, 'music/Chopin Etudes/Etude Op. 10 no. 3 in E major.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 10 no. 4 in C-sharp minor', 'Edward Neeman', null, 3, 'music/Chopin Etudes/Etude Op. 10 no. 4 in C-sharp minor.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 10 no. 5 in G-flar major', 'Edward Neeman', null, 4, 'music/Chopin Etudes/Etude Op. 10 no. 5 in G-flar major.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 10 no. 6 in E-flat minor', 'Edward Neeman', null, 5, 'music/Chopin Etudes/Etude Op. 10 no. 6 in E-flat minor.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 10 no. 7 in C major', 'Edward Neeman', null, 6, 'music/Chopin Etudes/Etude Op. 10 no. 7 in C major.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 10 no. 8 in F major', 'Edward Neeman', null, 7, 'music/Chopin Etudes/Etude Op. 10 no. 8 in F major.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 10 no. 9 in F minor', 'Edward Neeman', null, 8, 'music/Chopin Etudes/Etude Op. 10 no. 9 in F minor.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 10 no. 10 in A-flat major', 'Edward Neeman', null, 9, 'music/Chopin Etudes/Etude Op. 10 no. 10 in A-flat major.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 10 no. 11 in E-flat major', 'Edward Neeman', null, 10, 'music/Chopin Etudes/Etude Op. 10 no. 11 in E-flat major.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 10 no. 12 in C minor ''Revolutionary''', 'Edward Neeman', null, 0, 'music/Chopin Etudes/Etude Op. 10 no. 12 in C minor ''Revolutionary''.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 25 no.1 in A-flat major', 'Edward Neeman', null, 11, 'music/Chopin Etudes/Etude Op. 25 no.1 in A-flat major.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 25 no.2 in F minor', 'Edward Neeman', null, 12, 'music/Chopin Etudes/Etude Op. 25 no.2 in F minor.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 25 no. 3 in F major', 'Edward Neeman', null, 13, 'music/Chopin Etudes/Etude Op. 25 no. 3 in F major.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 25 no. 4 in A minor', 'Edward Neeman', null, 14, 'music/Chopin Etudes/Etude Op. 25 no. 4 in A minor.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 25 no. 5 in E minor', 'Edward Neeman', null, 15, 'music/Chopin Etudes/Etude Op. 25 no. 5 in E minor.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 25 no. 6 in G-sharp minor', 'Edward Neeman', null, 16, 'music/Chopin Etudes/Etude Op. 25 no. 6 in G-sharp minor.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 25 no. 7 in C-sharp minor', 'Edward Neeman', null, 17, 'music/Chopin Etudes/Etude Op. 25 no. 7 in C-sharp minor.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 25 no. 8 in D-flat major', 'Edward Neeman', null, 18, 'music/Chopin Etudes/Etude Op. 25 no. 8 in D-flat major.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 25 no. 9 in G-flat major', 'Edward Neeman', null, 19, 'music/Chopin Etudes/Etude Op. 25 no. 9 in G-flat major.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 25 no. 10 in B minor', 'Edward Neeman', null, 20, 'music/Chopin Etudes/Etude Op. 25 no. 10 in B minor.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 25 no. 11 in A minor', 'Edward Neeman', null, 21, 'music/Chopin Etudes/Etude Op. 25 no. 11 in A minor.mp3');
INSERT INTO Songs (title, artist, date, track, path) VALUES ('Etude Op. 25 no. 12 in C minor', 'Edward Neeman', null, 22, 'music/Chopin Etudes/Etude Op. 25 no. 12 in C minor.mp3');

INSERT INTO AlbumSong (song_id, album_id) VALUES (1, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (2, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (3, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (4, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (5, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (6, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (7, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (8, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (9, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (10, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (11, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (12, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (13, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (14, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (15, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (16, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (17, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (18, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (19, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (20, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (21, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (22, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (23, 1);
INSERT INTO AlbumSong (song_id, album_id) VALUES (24, 1);
INSERT INTO PlaylistSong (song_id, playlist_id) VALUES (1, 1);
INSERT INTO PlaylistSong (song_id, playlist_id) VALUES (4, 1);
INSERT INTO PlaylistSong (song_id, playlist_id) VALUES (8, 1);
INSERT INTO PlaylistSong (song_id, playlist_id) VALUES (11, 1);
INSERT INTO PlaylistSong (song_id, playlist_id) VALUES (14, 1);
INSERT INTO PlaylistSong (song_id, playlist_id) VALUES (17, 1);
INSERT INTO PlaylistSong (song_id, playlist_id) VALUES (20, 1);
