CREATE TABLE IF NOT EXISTS Songs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255),
    artist VARCHAR(255),
    date INTEGER,
    track INTEGER,
    path VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Albums (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Playlists (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS AlbumSong (
    song_id INT,
    album_id INT
);

CREATE TABLE IF NOT EXISTS PlaylistSong (
    song_id INT,
    playlist_id INT
);

